"""Settings API — first-run setup wizard endpoints."""

from __future__ import annotations

import logging
from contextlib import AsyncExitStack
from pathlib import Path

from fastapi import APIRouter
from pydantic import BaseModel

import config
from config import Settings
from mcp_client.manager import mcp_manager

logger = logging.getLogger(__name__)

router = APIRouter(prefix="/api/settings", tags=["settings"])

# .env lives at project root (one level above backend/)
_ENV_PATH = Path(__file__).resolve().parent.parent.parent / ".env"

# ---------------------------------------------------------------------------
# Request / Response models
# ---------------------------------------------------------------------------


class MaskedValues(BaseModel):
    anthropic_api_key: str
    meraki_api_key: str
    meraki_org_id: str
    te_token: str


class SetupStatus(BaseModel):
    needs_setup: bool
    meraki_connected: bool
    thousandeyes_connected: bool
    current_values: MaskedValues


class SetupRequest(BaseModel):
    anthropic_api_key: str
    meraki_api_key: str
    meraki_org_id: str
    te_token: str = ""


class SetupResponse(BaseModel):
    success: bool
    message: str
    meraki_connected: bool
    thousandeyes_connected: bool


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

_ENV_TEMPLATE = """\
# === AgenticOps .env ===
# Generated by the setup wizard. Edit freely.

# --- LLM ---
ANTHROPIC_API_KEY={anthropic_api_key}

# --- Meraki MCP (stdio subprocess) ---
MERAKI_API_KEY={meraki_api_key}
MERAKI_ORG_ID={meraki_org_id}
MERAKI_MCP_SCRIPT=Meraki Magic MCP/meraki-mcp-dynamic.py
MERAKI_MCP_VENV_FASTMCP=Meraki Magic MCP/.venv/bin/fastmcp
MERAKI_ACTIVE_PROFILE=default

# --- Meraki tuning ---
ENABLE_CACHING=true
CACHE_TTL_SECONDS=3600
READ_ONLY_MODE=false
ENABLE_FILE_CACHING=true
MAX_RESPONSE_TOKENS=5000
MAX_PER_PAGE=100

# --- ThousandEyes MCP (Streamable HTTP) ---
TE_MCP_URL=https://api.thousandeyes.com/mcp
TE_TOKEN={te_token}

# --- Server ---
HOST=0.0.0.0
PORT=8080
"""


def _mask(value: str, visible: int = 4) -> str:
    """Mask a secret, showing only the last *visible* characters."""
    if not value:
        return ""
    if len(value) <= visible:
        return "*" * len(value)
    return "*" * 8 + value[-visible:]


def _needs_setup() -> bool:
    """Return True when .env is missing or essential keys are blank."""
    if not _ENV_PATH.exists():
        return True
    s = config.settings
    return not s.anthropic_api_key or not s.meraki_api_key


def _reload_settings() -> None:
    """Re-read .env into the existing singleton so every module sees changes."""
    new = Settings()
    for field in Settings.model_fields:
        setattr(config.settings, field, getattr(new, field))


# ---------------------------------------------------------------------------
# Endpoints
# ---------------------------------------------------------------------------


@router.get("", response_model=SetupStatus)
async def get_settings_status():
    """Check whether first-run setup is needed. Returns masked current values."""
    s = config.settings
    return SetupStatus(
        needs_setup=_needs_setup(),
        meraki_connected=mcp_manager.meraki_connected,
        thousandeyes_connected=mcp_manager.te_connected,
        current_values=MaskedValues(
            anthropic_api_key=_mask(s.anthropic_api_key),
            meraki_api_key=_mask(s.meraki_api_key),
            meraki_org_id=s.meraki_org_id,  # not a secret
            te_token=_mask(s.te_token),
        ),
    )


@router.post("/setup", response_model=SetupResponse)
async def run_setup(req: SetupRequest):
    """Write .env from template, reload settings, and (re)connect MCP."""
    try:
        # Use existing value when the user leaves a field empty
        s = config.settings
        anthropic_key = req.anthropic_api_key or s.anthropic_api_key
        meraki_key = req.meraki_api_key or s.meraki_api_key
        meraki_org = req.meraki_org_id or s.meraki_org_id
        te_tok = req.te_token or s.te_token

        # 1. Write .env
        content = _ENV_TEMPLATE.format(
            anthropic_api_key=anthropic_key,
            meraki_api_key=meraki_key,
            meraki_org_id=meraki_org,
            te_token=te_tok,
        )
        _ENV_PATH.write_text(content)
        logger.info(".env written to %s", _ENV_PATH)

        # 2. Reload settings singleton in-place
        _reload_settings()

        # 3. Disconnect existing MCP sessions (best-effort) and reconnect
        try:
            await mcp_manager.disconnect()
        except Exception:
            logger.warning("Error during MCP disconnect (continuing with reconnect)", exc_info=True)
        # Ensure a fresh exit stack regardless of how disconnect went
        mcp_manager._exit_stack = AsyncExitStack()
        mcp_manager._meraki_session = None
        mcp_manager._te_session = None
        mcp_manager._tools.clear()
        mcp_manager._tool_map.clear()
        await mcp_manager.connect()

        return SetupResponse(
            success=True,
            message="Setup complete — MCP servers connected.",
            meraki_connected=mcp_manager.meraki_connected,
            thousandeyes_connected=mcp_manager.te_connected,
        )
    except Exception:
        logger.exception("Setup failed")
        return SetupResponse(
            success=False,
            message="Setup failed — check backend logs for details.",
            meraki_connected=mcp_manager.meraki_connected,
            thousandeyes_connected=mcp_manager.te_connected,
        )
